from ex0 import FlameFactory, AquaFactory
from ex1 import HealingCreatureFactory, TransformCreatureFactory
from ex2 import NormalStrategy, AggresiveStrategy, DefensiveStrategy, CreatureError


def main() -> None:

    flame_factory = FlameFactory()
    aqua_factory = AquaFactory()
    healing_factory = HealingCreatureFactory()
    transform_factory = TransformCreatureFactory()
    print("Tournament 0 (basic)")
    fire_creature = flame_factory.create_base()
    water_creature = aqua_factory.create_base()
    transforming_creature = transform_factory.create_base()
    healing_creature = healing_factory.create_base()
    normal_strategy = NormalStrategy()
    defensive_strategy = DefensiveStrategy()
    aggresive_strategy = AggresiveStrategy()
    print(" [ (Flameling+Normal), (Healing+Defensive) ]")
    print("*** Tournament ***")
    print("2 opponents involved")
    print()
    print("* Battle *")
    print(fire_creature.describe())
    print(" vs.")
    print(healing_creature.describe())
    print(" now fight!")
    normal_strategy.act(fire_creature)
    defensive_strategy.act(healing_creature)
    print()
    print("Tournament 1 (error)")
    print(" [ (Flameling+Aggressive), (Healing+Defensive) ]")
    print("*** Tournament ***")
    print("2 opponents involved")
    print()
    print("* Battle *")
    print(fire_creature.describe())
    print(" vs.")
    print(healing_creature.describe())
    print(" now fight!")
    try:
        aggresive_strategy.act(fire_creature)
    except CreatureError as e:
        print(f"Battle error, aborting tournament: {e}")
    print()
    print("Tournament 2 (multiple)")
    print(" [ (Aquabub+Normal), (Healing+Defensive), (Transform+Aggressive) ]")
    print("*** Tournament ***")
    print("3 opponents involved")
    print()
    print("* Battle *")
    print(water_creature.describe())
    print(" vs.")
    print(healing_creature.describe())
    print(" now fight!")
    normal_strategy.act(water_creature)
    defensive_strategy.act(healing_creature)
    print()
    print("* Battle *")
    print(water_creature.describe())
    print(" vs.")
    print(transforming_creature.describe())
    print(" now fight!")
    normal_strategy.act(water_creature)
    aggresive_strategy.act(transforming_creature)
    print()
    print("* Battle *")
    print(healing_creature.describe())
    print(" vs.")
    print(transforming_creature.describe())
    print(" now fight!")
    defensive_strategy.act(healing_creature)
    aggresive_strategy.act(transforming_creature)

if __name__ == "__main__":
	main()
      